---
- name: Patch OS
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Update package cache
      dnf:
        update_cache: yes
      when: ansible_distribution == 'AlmaLinux' or ansible_distribution == 'RedHat'

    - name: Upgrade packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Upgrade packages
      dnf:
        name: '*'
        state: latest
      when: ansible_distribution == 'AlmaLinux' or ansible_distribution == 'RedHat'
