---
- name: Collect OS Information
  hosts: all
  gather_facts: yes
  become: true

  tasks:
    - name: Display OS Information
      debug:
        msg: |
          OS: {{ ansible_distribution | default('Unknown') }}
          Version: {{ ansible_distribution_version | default('Unknown') }}
          Architecture: {{ ansible_architecture | default('Unknown') }}
          Kernel: {{ ansible_kernel | default('Unknown') }}